server:
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    default: local

  config:
    import:
      - optional:file:../.env[.properties]

  application:
    name: ${SPRING_APPLICATION_NAME:prodio}

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    repair-on-migrate: true

  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true
      republish-outstanding-events-on-restart: true

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, threaddump
  metrics:
    tags:
      application: prodio-backend

prodio:
  cors:
    allowed-origins: ${PRODIO_CORS_ALLOWED_ORIGINS:http://localhost:3000}

  security:
    csrf:
      secure-cookie: ${PRODIO_CSRF_SECURE_COOKIE:false}
