### [Order] 수주 목록 조회
GET http://localhost:8080/api/orders
Content-Type: application/json

###

### [Order] 수주 단건 조회
GET http://localhost:8080/api/orders/1
Content-Type: application/json

###

### [Order] 수주 등록
POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "clientId": 1,
  "productId": 1,
  "quantity": 100,
  "dueDate": "2026-09-01"
}

###

### [Order] 수주 상태 변경 (칸반)
PATCH http://localhost:8080/api/orders/1/status
Content-Type: application/json

{
  "status": "IN_PRODUCTION"
}
